### ISSUE TITLE
Google Play says my device is not compatible.

### ISSUE THREAD

**Issue by justinmeiners** [MyEtherWallet/MEWconnect-Android#4]
I have a MotoX (motorola XT1094)  which is a fairly capable phone. I have never seen an app which was not compatible. This brought up a few questions:

Are there special hardware features which the app needs?

Are you targeting a few phones to make sure you can provide a good experience for those devices?

Do you have a published list of supported devices?

**Comment by bartwell** [comment]
Hi @justinmeiners,

Could you please provide more info about your device?

1. Android version
2. Firmware info

**Comment by justinmeiners** [comment]
1. Android 5.1

2. What firmware info do you want? Kernel 3.4.42

**Comment by bartwell** [comment]
@justinmeiners Your device must have an Android version equal or greater 6 (Marshmallow). That is the reason of incompatibility.
