### ISSUE TITLE
Fingerprint support

### ISSUE THREAD

**Issue by Player-126** [MyEtherWallet/MEWconnect-Android#5]
Please add fingerprint support to unlock wallet without password.

**Comment by kennethffx2** [comment]
> Please add fingerprint support to unlock wallet without password.

Yes, this should be a standard feature with today's phones.
Galaxy S10 user here and I love using my thumb to get into my bank apps.

**Comment by WhiteCrayon00** [comment]
Open

**Comment by WhiteCrayon00** [comment]
How do i add the fingerprint to it
