### ISSUE TITLE
Can't screenshot backup seed

### ISSUE THREAD

**Issue by JonahGroendal** [MyEtherWallet/MEWconnect-Android#7]
The backup wallet seed page blocks screenshots. Of course this is for security, but I'm just using the ropsten testnet. And I'm not a baby, let me control my own device and make my own decisions. You have a warning at the bottom saying "don't screenshot" which imo is enough. As a crypto anarchist person I detest restrictions like this and I'm guessing other crypto people do too. I'm also of the opinion that writing down a seed by hand is dangerous, since I've almost lost ether in another app by mistaking "guitar sting" for "guitar string" because that's how human brains work.

**Comment by kvhnuke** [comment]
Hi @JonahGroendal 
we value your opinion and we totally understand you are familiar with Ethereum. However, MEWconnect is mainly meant for new comers and it is our goal to show them the best security practices. Unfortunately your request is not something we can accomadate as we fear it'll expose the mnemonic to 3rd party services via photo sharing apps and other cloud backup methods. We value your input and therefore, if you are familiar with compiling android application you can take out the screenshot block and compile your own version of MEWconnect

**Comment by JonahGroendal** [comment]
As a developer I've found many features of MEW very useful, including ENS registration and I see you can interact with contracts now. That doesn't really seem like beginner stuff, and even though I could do all this by hand mew is way more convenient. Great app, I'll still use it, but this is just a small gripe I have with it. Thanks for listening

**Comment by JonahGroendal** [comment]
Oh wait the app doesn't have those features, nevermind.
