### ISSUE TITLE
not showing eth balance

### ISSUE THREAD

**Issue by JonahGroendal** [MyEtherWallet/MEWconnect-Android#8]
Using the Ropsten testnet, the app shows 0 balance but I transferred 1 eth to the address generated by the app. I verified the actual balance (1 eth) using etherscan. I did the transfer yesterday but it's still not showing up.

**Comment by JonahGroendal** [comment]
Connecting to the myetherwallet.com ROP network on the MEW web app produces the same problem, and it shows the block number is stuck on 5515743. Could be a problem with the myetherwallet.com RPC endpoint because connecting to the infura-ws ROP network works just fine.

**Comment by Foboz** [comment]
Fixed. Thanks @JonahGroendal
